### PR TITLE
athena support

### PR DESCRIPTION
**Pull request by frolovv**

### CODE REVIEW

**Comment by frolovv** [comment]
@antonpod @sthuck this PR should add support for athena notes to quix-backend.

there are several breaking changes : 
1) `/execute/v1/sql` was split to `/execute/v1/presto` and `/execute/v1/athena`

2) `/api/db/...` was split to `/api/presto/db/...` and `/api/athena/db/...` (athena db tree is not yet implemented)

3) `.env` should have few new keys 
```
MODULES=presto,athena

ATHENA_OUTPUT=
ATHENA_REGION=
ATHENA_DATABASE=
```

4) athena credentials are fetched via `DefaultAWSCredentialsProviderChain` (https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html)

**Comment by antonpod** [comment]
@sthuck please change the quixConfig in index.vm to:
```js
window.quixConfig = {
  staticsBaseUrl: '',
  auth: {
    googleClientId: '<google client id>'
  },
  executor: {
    url: '<backend url>'
  },
  modules: [{name: 'presto'}, {name: 'athena'}] // fetch this config from backend
};
```

@frolovv

**Comment by frolovv** [comment]
added `api/db/config` that will return today: 
```
{
   "trees" : ["presto"]
}
```

and once we support athena db tree : 
```
{
   "trees" : ["presto", "athena"]
}
```

**Comment by antonpod** [comment]
@frolovv please change:
- `/api/presto/db/` to `/api/db/presto`
- `/api/athena/db/` to `/api/db/athena`

to support this proxy format https://github.com/wix/quix/blob/master/quix-frontend/service/src/modules/proxy-backend/proxy-backend.module.ts#L23

**Pull request merged**
