### PR TITLE
Add python note

### PR DESCRIPTION
**Pull request by frolovv**

### CODE REVIEW

**Comment by frolovv** [comment]
@antonpod it seems like every engine has to implement DB : 
https://github.com/wix/quix/blob/f9c115d9c906669748dc2496b57d1059ef75f5f8/quix-frontend/client/src/plugins/plugin-factory.ts#L7-L18

python is one of the examples of engines that doesn't expose any DB.

right now this error is fatal and app can't load : 
image

**Comment by antonpod** [comment]
> @antonpod it seems like every engine has to implement DB :
> https://github.com/wix/quix/blob/f9c115d9c906669748dc2496b57d1059ef75f5f8/quix-frontend/client/src/plugins/plugin-factory.ts#L7-L18
> 

resolved

**Comment by frolovv** [comment]
@antonpod execution works great, but the console tab is blank

try running the following : 
```python
from quix import Quix
q = Quix()

print(123)

q.fields([1,2,3])
q.row([4,5,6])
q.row([4,5,6])
q.row([4,5,6])
q.row([4,5,6])
q.row([4,5,6])
q.row([4,5,6])
q.row([4,5,6])
```

**Comment by frolovv** [comment]
@antonpod looks like playground doesn't have console tab 
image

**Comment by frolovv** [comment]
@antonpod 

issue : 
socket is killed, but execution timer doesn't stop.

how to reproduce : 
1) execute 
```python
import time
print(123)
time.sleep(60)
print(456)
```

2) click stop after first line is printed

3) timer doesn't stop

python-doesnnot-stop

**Comment by frolovv** [comment]
@antonpod suggestion : let's add timestamp to each log line in the console

**Comment by frolovv** [comment]
> @antonpod
> 
> issue :
> socket is killed, but execution timer doesn't stop.
> 
> how to reproduce :
> 
>     1. execute
> 
> 
> ```python
> import time
> print(123)
> time.sleep(60)
> print(456)
> ```
> 
>     1. click stop after first line is printed
> 
>     2. timer doesn't stop
> 
> 
> python-doesnnot-stop

@antonpod i think that the socket is killed on "Stop" button, so the `query-end` and `end` events can't be sent from backend

**Comment by antonpod** [comment]
> > @antonpod
> > issue :
> > socket is killed, but execution timer doesn't stop.
> > how to reproduce :
> > ```
> > 1. execute
> > ```
> > 
> > 
> > ```python
> > import time
> > print(123)
> > time.sleep(60)
> > print(456)
> > ```
> > 
> > 
> > ```
> > 1. click stop after first line is printed
> > 
> > 2. timer doesn't stop
> > ```
> > 
> > 
> > python-doesnnot-stop
> 
> @antonpod i think that the socket is killed on "Stop" button, so the `query-end` and `end` events can't be sent from backend

Fixed and looking amazing.

**Pull request merged**
